/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Answer {
  a_desc: string | null;
  a_order: number;
  a_text: string;
  a_type: string | null;
  calls_page_id: number | null;
  doc_id: number | null;
  id: Generated<number>;
  question_id: number;
}

export interface Checklist {
  id: Generated<number>;
  name: string;
}

export interface Doc {
  alias: string;
  filename: string;
  id: Generated<number>;
}

export interface Page {
  hidden: Generated<boolean>;
  id: Generated<number>;
  title: string;
}

export interface PageInstance {
  checklist_id: number;
  id: Generated<number>;
  page_id: number;
}

export interface PageInstanceParent {
  instance_id: number;
  parent_instance_id: number | null;
}

export interface Question {
  doc_id: number | null;
  id: Generated<number>;
  page_id: number;
  q_desc: string | null;
  q_text: string;
  q_type: string;
}

export interface DB {
  answer: Answer;
  checklist: Checklist;
  doc: Doc;
  page: Page;
  page_instance: PageInstance;
  page_instance_parent: PageInstanceParent;
  question: Question;
}
