/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Answer {
  additional_info_num_lines: number | null;
  additional_info_placeholder: string | null;
  calls_instance_id: number | null;
  description_image_url: string | null;
  description_text: string | null;
  has_additional_info: Generated<boolean | null>;
  hidden: Generated<boolean | null>;
  id: Generated<number>;
  position: number;
  question_id: number;
  text: string;
}

export interface Checklist {
  id: Generated<number>;
  name: string;
}

export interface ClaimDummy {
  checklist_id: number;
  claim_amount: Numeric | null;
  claim_number: string | null;
  client: string | null;
  client_adjuster: string | null;
  date_of_loss: Timestamp | null;
  expected_recovery: Numeric | null;
  id: Generated<number>;
  insured: string | null;
  last_update: Timestamp | null;
  last_updated_by: string | null;
  loss_location: string | null;
  total_incurred: Numeric | null;
}

export interface Doc {
  alias: string;
  filename: string;
  id: Generated<number>;
}

export interface Page {
  hidden: Generated<boolean>;
  id: Generated<number>;
  title: string;
}

export interface PageInstance {
  checklist_id: number;
  id: Generated<number>;
  page_id: number;
  parent_instance_id: number | null;
}

export interface Question {
  description_image_url: string | null;
  description_text: string | null;
  hidden: Generated<boolean | null>;
  id: Generated<number>;
  num_lines: number | null;
  page_id: number;
  placeholder: string | null;
  text: string;
  type: string;
}

export interface QuestionResponse {
  checklist_id: number;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  instance_id: number;
  question_id: number;
  response_text: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface QuestionResponseAnswer {
  additional_info: string | null;
  answer_id: number;
  id: Generated<number>;
  response_id: number;
}

export interface ResponseAuditLogs {
  action: string;
  checklist_id: number;
  id: Generated<number>;
  instance_id: number;
  new_additional_info: Json | null;
  new_answer_ids: Json | null;
  new_response_text: string | null;
  old_additional_info: Json | null;
  old_answer_ids: Json | null;
  old_response_text: string | null;
  question_id: number;
  response_id: number | null;
  timestamp: Generated<Timestamp | null>;
  user_id: number;
}

export interface DB {
  answer: Answer;
  checklist: Checklist;
  claim_dummy: ClaimDummy;
  doc: Doc;
  page: Page;
  page_instance: PageInstance;
  question: Question;
  question_response: QuestionResponse;
  question_response_answer: QuestionResponseAnswer;
  response_audit_logs: ResponseAuditLogs;
}
