/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  expires_at: number | null;
  id: Generated<number>;
  id_token: string | null;
  provider: string;
  provider_account_id: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  user_id: string;
}

export interface Action {
  answer_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  definition: Json;
  id: Generated<number>;
  type: string;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface ActionLog {
  action_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  status: string;
}

export interface AdminActionLogs {
  action: string;
  client_id: string;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_name: string;
  id: Generated<number>;
  user_id: string;
  value: Json | null;
}

export interface Answer {
  additional_info_num_lines: number | null;
  additional_info_placeholder: string | null;
  /**
   * Comma-separated list of allowed file extensions (e.g., '.pdf,.docx,.jpg'). NULL means all allowed file types are permitted
   */
  allowed_extensions: string | null;
  calls_instance_id: number | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  description_image_url: string | null;
  description_text: string | null;
  grade: Numeric | null;
  has_additional_info: Generated<boolean | null>;
  hidden: Generated<boolean | null>;
  id: Generated<number>;
  position: number;
  question_id: number;
  /**
   * When true, this answer requires the user to upload a file instead of providing free-form text
   */
  requires_upload: Generated<boolean | null>;
  text: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface AuthEvents {
  created_at: Generated<Timestamp>;
  event_details: Json | null;
  event_type: string;
  id: Generated<string>;
  ip_address: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface Checklist {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  name: string;
  published: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ChecklistClaim {
  assignee: string | null;
  checklist_id: number;
  claim_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  last_opened: Generated<Timestamp>;
  /**
   * JSONB snapshot of key decisions and answers when checklist is submitted
   */
  outcome_snapshot: Json | null;
  status: string;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  /**
   * Auto-calculated days from created_at to submitted_at
   */
  time_to_resolution_days: number | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Claim {
  /**
   * Sum of all recovery_event amounts for this claim
   */
  actual_recovery: Numeric | null;
  claim_amount: Numeric | null;
  claim_number: string | null;
  client: string | null;
  client_adjuster: string | null;
  client_id: string;
  created_at: Timestamp | null;
  created_by: string | null;
  date_of_loss: Timestamp | null;
  expected_recovery: Numeric | null;
  feed_id: number | null;
  id: Generated<number>;
  insured: string | null;
  last_update: Timestamp | null;
  last_updated_by: string | null;
  loss_location: string | null;
  /**
   * Current status of recovery efforts: pending, in_progress, recovered, closed_no_recovery
   */
  recovery_status: string | null;
  total_incurred: Numeric | null;
}

export interface Client {
  id: Generated<string>;
  name: string;
}

export interface Comment {
  body: string;
  checklist_id: number;
  claim_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  instance_id: number | null;
  question_id: number | null;
  updated_at: Timestamp | null;
}

export interface Deadline {
  claim_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  deadline_date: Timestamp;
  deadline_type: string;
  description: string | null;
  id: Generated<number>;
  status: Generated<string>;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface Doc {
  alias: string;
  answer_id: number | null;
  claim_id: number | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  deadline_id: number | null;
  description: string | null;
  doc_group_id: number | null;
  /**
   * Workflow status: draft, pending_review, approved, archived
   */
  doc_status: Generated<string>;
  /**
   * Categorical classification of document
   */
  doc_type: Generated<string>;
  file_size: Int8 | null;
  filename: string;
  id: Generated<number>;
  /**
   * Flag to identify the latest version
   */
  is_current_version: Generated<boolean | null>;
  mime_type: string | null;
  page_instance_id: number | null;
  preview_url: string | null;
  question_id: number | null;
  recovery_event_id: number | null;
  /**
   * Previous version of this document (if applicable)
   */
  replaces_doc_id: number | null;
  /**
   * Reference to question_response when this document is uploaded as part of a response to a question requiring file upload
   */
  response_doc_id: number | null;
  /**
   * Azure Blob Storage key/path for the document
   */
  storage_key: string;
  title: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
  /**
   * Version number for document versioning
   */
  version: Generated<number | null>;
}

export interface DocGroup {
  /**
   * Associated claim for auto-created claim folders
   */
  claim_id: number | null;
  client_id: string;
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  /**
   * claim_folder (auto-created), category (system), or custom (user-created)
   */
  group_type: Generated<string>;
  icon: string | null;
  id: Generated<number>;
  name: string;
  /**
   * Parent group for hierarchical folder structure
   */
  parent_group_id: number | null;
  sort_order: Generated<number | null>;
  updated_at: Timestamp | null;
  updated_by: string | null;
  /**
   * Links user folders to their owner. Used to display user name/email in Documents tab for folders under Users/
   */
  user_id: string | null;
}

export interface DocRequirement {
  checklist_id: number | null;
  claim_id: number | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<number>;
  is_required: Generated<boolean | null>;
  required_doc_type: string;
  requirement_name: string;
}

export interface DocRequirementFulfillment {
  doc_id: number | null;
  doc_requirement_id: number;
  fulfilled_at: Generated<Timestamp>;
  fulfilled_by: string;
  id: Generated<number>;
  manually_marked_complete: Generated<boolean | null>;
  notes: string | null;
}

export interface Feeds {
  client_id: string;
  connection_options: Json;
  created_at: Generated<Timestamp>;
  created_by: string;
  feed_type: string;
  id: Generated<number>;
  last_synced_at: Timestamp | null;
  name: string;
  schedule: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Page {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  hidden: Generated<boolean>;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface PageInstance {
  checklist_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  page_id: number;
  parent_instance_id: number | null;
  position: number;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PageInstanceStatus {
  claim_id: number;
  client_id: string;
  id: Generated<number>;
  page_instance_id: number;
  status: string;
  template_version: number;
  updated_at: Generated<Timestamp | null>;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token: string;
  used: Generated<boolean>;
  user_id: string;
}

export interface Question {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  description_image_url: string | null;
  description_text: string | null;
  hidden: Generated<boolean | null>;
  id: Generated<number>;
  page_id: number;
  placeholder: string | null;
  position: number;
  text: string;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface QuestionResponse {
  checklist_id: number;
  claim_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  instance_id: number;
  question_id: number | null;
  /**
   * Reference to uploaded document when answer requires file upload
   */
  response_doc_id: number | null;
  response_text: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface QuestionResponseAnswer {
  additional_info: string | null;
  answer_id: number | null;
  id: Generated<number>;
  response_id: number;
}

export interface RecoveryEvent {
  claim_id: number;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  notes: string | null;
  recovery_amount: Numeric;
  recovery_date: Timestamp;
  recovery_source: string | null;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface ResponseAuditLogs {
  action: string;
  checklist_id: number | null;
  claim_id: number | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  /**
   * Expert confidence level (0-1) for AI training metadata
   */
  decision_confidence: Numeric | null;
  /**
   * Expert reasoning for AI training (distinct from operational additional_info)
   */
  decision_rationale: string | null;
  /**
   * Marks high-quality responses suitable for AI training data
   */
  expert_flag: Generated<boolean>;
  id: Generated<number>;
  instance_id: number | null;
  new_answers: Generated<Json>;
  new_response_text: string | null;
  old_answers: Generated<Json>;
  old_response_text: string | null;
  page_label: string;
  question_id: number | null;
  question_text: string;
  response_id: number | null;
  user_id: string | null;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<number>;
  session_token: string;
  user_id: string;
}

export interface Users {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  disabled: Generated<boolean>;
  email: string;
  email_verified: Timestamp | null;
  first: string;
  id: Generated<string>;
  last: string;
  last_login: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  mfa_secret: string | null;
  must_change_password: Generated<boolean>;
  onboarding_email_sent: Generated<boolean>;
  password_hash: string;
  phone: string | null;
  phone_verified: Timestamp | null;
  role: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface VerificationTokens {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  accounts: Accounts;
  action: Action;
  action_log: ActionLog;
  admin_action_logs: AdminActionLogs;
  answer: Answer;
  auth_events: AuthEvents;
  checklist: Checklist;
  checklist_claim: ChecklistClaim;
  claim: Claim;
  client: Client;
  comment: Comment;
  deadline: Deadline;
  doc: Doc;
  doc_group: DocGroup;
  doc_requirement: DocRequirement;
  doc_requirement_fulfillment: DocRequirementFulfillment;
  feeds: Feeds;
  page: Page;
  page_instance: PageInstance;
  page_instance_status: PageInstanceStatus;
  password_reset_tokens: PasswordResetTokens;
  question: Question;
  question_response: QuestionResponse;
  question_response_answer: QuestionResponseAnswer;
  recovery_event: RecoveryEvent;
  response_audit_logs: ResponseAuditLogs;
  sessions: Sessions;
  users: Users;
  verification_tokens: VerificationTokens;
}
