-- Additional indexes derived from query analysis
CREATE INDEX IF NOT EXISTS idx_users_client_disabled_name ON users (client_id, disabled, last, first);
CREATE INDEX IF NOT EXISTS idx_users_client_last_login ON users (client_id, last_login);
CREATE INDEX IF NOT EXISTS idx_checklist_client_published ON checklist (client_id, published);
CREATE INDEX IF NOT EXISTS idx_checklist_lower_name ON checklist (lower(name));
CREATE INDEX IF NOT EXISTS idx_feeds_client_status ON feeds (client_id, status);
CREATE INDEX IF NOT EXISTS idx_claim_client_feed ON claim (client_id, feed_id);
CREATE INDEX IF NOT EXISTS idx_claim_client_created_at ON claim (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_checklist_claim_claim_id ON checklist_claim (claim_id);
CREATE INDEX IF NOT EXISTS idx_checklist_claim_client_status ON checklist_claim (client_id, status);
CREATE INDEX IF NOT EXISTS idx_checklist_claim_client_assignee ON checklist_claim (client_id, assignee);
CREATE INDEX IF NOT EXISTS idx_checklist_claim_client_created_at ON checklist_claim (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_page_client_hidden ON page (client_id, hidden);
CREATE INDEX IF NOT EXISTS idx_page_instance_client_checklist_parent ON page_instance (client_id, checklist_id, parent_instance_id);
CREATE INDEX IF NOT EXISTS idx_doc_client ON doc (client_id);
CREATE INDEX IF NOT EXISTS idx_question_client_page ON question (client_id, page_id);
CREATE INDEX IF NOT EXISTS idx_answer_client_question_position ON answer (client_id, question_id, position);
CREATE INDEX IF NOT EXISTS idx_answer_client_calls_instance ON answer (client_id, calls_instance_id);
CREATE INDEX IF NOT EXISTS idx_question_response_client_scope ON question_response (client_id, checklist_id, claim_id, instance_id);
CREATE INDEX IF NOT EXISTS idx_qra_response_id ON question_response_answer (response_id);
CREATE INDEX IF NOT EXISTS idx_qra_answer_id ON question_response_answer (answer_id);
CREATE INDEX IF NOT EXISTS idx_response_audit_logs_client_created_at ON response_audit_logs (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_response_audit_logs_scope ON response_audit_logs (client_id, checklist_id, claim_id);
CREATE INDEX IF NOT EXISTS idx_response_audit_logs_client_user ON response_audit_logs (client_id, user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_created_at ON password_reset_tokens (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_action_client_answer ON action (client_id, answer_id);
CREATE INDEX IF NOT EXISTS idx_action_log_client_action ON action_log (client_id, action_id);
CREATE INDEX IF NOT EXISTS idx_action_log_client_created_at ON action_log (client_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comment_scope ON comment (client_id, checklist_id, claim_id, instance_id);
CREATE INDEX IF NOT EXISTS idx_comment_client_question ON comment (client_id, question_id);
CREATE INDEX IF NOT EXISTS idx_comment_client_updated_at ON comment (client_id, updated_at DESC, created_at DESC);
