name: Trigger auto deployment for manifest-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/manifest-container-app-AutoDeployTrigger-c2e7f4ec-86e7-4601-9684-6928fed0af8d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MANIFESTCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MANIFESTCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MANIFESTCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and deploy Container App
        run: |
          az containerapp up \
            --name manifest-container-app \
            --resource-group DefaultResourceGroup-WUS2 \
            --source . \
            --ingress external \
            --target-port 8080 \
            --env-vars PORT=8080


